name: Cliam CI / CD pipeline
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v1
      - name: Setup node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '14.16'
      - name: Install global dependencies
        run: npm i typescript@4.2.2 -g
      - name: Install local dependencies
        run: npm i
      - name: Compile Typescript files with declarations
        run: tsc --declaration
      - name: Create .env file
        run: |
          touch .env
          echo EMAIL_FROM = "${{ secrets.EMAIL_FROM }}" >> .env
          echo EMAIL_REPLY_TO = "${{ secrets.EMAIL_REPLY_TO }}" >> .env
          echo EMAIL_TO = "${{ secrets.EMAIL_TO }}" >> .env
          echo MAILGUN_API_KEY = "${{ secrets.MAILGUN_API_KEY }}" >> .env
          echo MAILJET_API_KEY = "${{ secrets.MAILJET_API_KEY }}" >> .env
          echo MAILJET_TOKEN = "${{ secrets.MAILJET_TOKEN }}" >> .env
          echo POSTMARK_API_KEY = "${{ secrets.POSTMARK_API_KEY }}" >> .env
          echo SENDGRID_API_KEY = "${{ secrets.SENDGRID_API_KEY }}" >> .env
          echo SENDINBLUE_API_KEY = "${{ secrets.SENDINBLUE_API_KEY }}" >> .env
          echo SMTP_HOST = "${{ secrets.SMTP_HOST }}" >> .env
          echo SMTP_USERNAME = "${{ secrets.SMTP_USERNAME }}" >> .env
          echo SMTP_PASSWORD = "${{ secrets.SMTP_PASSWORD }}" >> .env
          echo SPARKPOST_API_KEY = "${{ secrets.SPARKPOST_API_KEY }}" >> .env
      - name: Show environment
        run: cat .env
      - name: Execute tests sets
        run: npm run ci:coverage
      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./reports/coverage/lcov.info
      - name: Delete unpackaged files
        run: rm -rf ./.github && rm -rf ./src && rm -rf ./test && rm -f tsconfig.json && rm -f ROADMAP.md
      - name: Fix typing export
        run: |
          printf "import { Cliam } from './classes/cliam.class';\nexport = Cliam;" > ./lib/index.d.ts
      - name: Publish package on NPM registery
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}