name: Cliam CI / CD pipeline
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v1
      - name: Setup node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '14.16'
      - name: Install global dependencies
        run: npm i typescript@4.2.2 -g
      - name: Install local dependencies
        run: npm i
      - name: Compile Typescript files with declarations
        run: tsc --declaration
      - name: Create .env file
        run: |
          touch .env
          printf  EMAIL_FROM = "${{ secrets.EMAIL_FROM }}"
                  EMAIL_REPLY_TO = "${{ secrets.EMAIL_REPLY_TO }}"
                  EMAIL_TO = "${{ secrets.EMAIL_TO }}"
                  MAILGUN_API_KEY = "${{ secrets.MAILGUN_API_KEY }}"
                  MAILJET_API_KEY = "${{ secrets.MAILJET_API_KEY }}"
                  MAILJET_TOKEN = "${{ secrets.MAILJET_TOKEN }}"
                  POSTMARK_API_KEY = "${{ secrets.POSTMARK_API_KEY }}"
                  SENDGRID_API_KEY = "${{ secrets.SENDGRID_API_KEY }}"
                  SENDINBLUE_API_KEY = "${{ secrets.SENDINBLUE_API_KEY }}"
                  SMTP_HOST = "${{ secrets.SMTP_HOST }}"
                  SMTP_USERNAME = "${{ secrets.SMTP_USERNAME }}"
                  SMTP_PASSWORD = "${{ secrets.SMTP_PASSWORD }}"
                  SPARKPOST_API_KEY = "${{ secrets.SPARKPOST_API_KEY }}" > .env
      - name: Execute tests sets
        run: npm run ci:test
      - name: Share code coverage
        run: npm run ci:coverage
      - name: Delete unpackaged files
        run: rm -rf ./.github && rm -rf ./src && rm -rf ./test && rm -f tsconfig.json && rm -f ROADMAP.md
      - name: Fix typing export
        run: |
          printf "import { Cliam } from './classes/cliam.class';\nexport = Cliam;" > ./lib/index.d.ts
      - name: Publish package on NPM registery
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}